# Generated by Django 3.0.6 on 2020-05-26 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sky_url', models.URLField()),
                ('home_odds', models.FloatField(null=True)),
                ('draw_odds', models.FloatField(null=True)),
                ('away_odds', models.FloatField(null=True)),
                ('kick_off', models.TimeField(null=True)),
                ('home_team', models.CharField(default='Home', max_length=150)),
                ('away_team', models.CharField(default='Away', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Matches',
            },
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_odds', models.FloatField(null=True)),
                ('draw_odds', models.FloatField(null=True)),
                ('away_odds', models.FloatField(null=True)),
                ('home_score', models.IntegerField(null=True)),
                ('away_score', models.IntegerField(null=True)),
                ('minutes', models.FloatField(null=True)),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='sky.Match')),
            ],
            options={
                'verbose_name_plural': 'Statistics',
            },
        ),
    ]
