# Generated by Django 3.0.6 on 2020-05-17 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sky', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Odds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_odds', models.CharField(max_length=8)),
                ('draw_odds', models.CharField(max_length=8)),
                ('away_odds', models.CharField(max_length=8)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sky.Match')),
            ],
            options={
                'verbose_name_plural': 'Odds',
            },
        ),
    ]
