# Generated by Django 3.0.6 on 2020-05-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sky', '0002_odds'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='away_odds',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='draw_odds',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='home_odds',
            field=models.FloatField(null=True),
        ),
    ]
