# Generated by Django 3.0.6 on 2020-05-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sky', '0003_auto_20200519_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='kick_off',
            field=models.TimeField(null=True),
        ),
        migrations.DeleteModel(
            name='Odds',
        ),
    ]
