# Generated by Django 3.0.6 on 2020-05-19 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sky', '0004_auto_20200519_2007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='url',
            new_name='sky_url',
        ),
    ]
