# Generated by Django 3.0.6 on 2020-05-24 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sky', '0005_auto_20200519_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='away_odds',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='statistics',
            name='draw_odds',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='statistics',
            name='home_odds',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='sky.Match'),
        ),
    ]
